# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: jzhong
email: jillianzhong@yahoo.com
description: >- # this means to ignore newlines until "baseurl:" Add your site description here in the _config.yml file. It will appear in your document head meta (for Google search results) and title of the website (in browser tabs).
  Jillian Zhong's portfolio website. Jillian Zhong is a designer, artist, and content creator based in New York City.

baseurl: "/" # the subpath of your site, e.g. /blog. leave blank if this is your main github pages repository
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
remote_theme: jirrian/jekyll-theme-image-grid@main

# generate social links in footer
social_links:
  twitter: 
  github: jirrian
  # facebook: jekyll
  instagram: 
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon

  # Mastodon instances
  # mastodon:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

collections:
  medium:
    output: true
  work:
    output: true

defaults:
  - scope:
      path: ""
      type: "medium"
    values:
      layout: "worksmedium"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"

plugins:
  - jekyll-seo-tag

include:
  - _images